# Generated by Django 2.1.3 on 2018-12-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(max_length=64, unique=True)),
                ('prefix', models.CharField(choices=[('?', '?'), ('!', '!'), (':', ':'), ('~', '~'), ('%', '%')], max_length=1)),
            ],
        ),
    ]
