# Generated by Django 2.1.3 on 2018-12-04 07:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None),
        ),
    ]
