# Generated by Django 2.1.3 on 2018-12-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_server_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='streaming_role',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='server',
            name='streaming_role_requires',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
