# Generated by Django 2.1.3 on 2018-12-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181205_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='name',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
