# Generated by Django 2.1.3 on 2018-12-07 23:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_server_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
